# -*- coding: utf-8 -*-
"""quiz project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igPONMTwWarRplHK-NoEJwJZ9TpNhwc3
"""

"""
╔══════════════════════════════════════════════════════╗
║           🐍  PYTHON QUIZ APP  🐍                    ║
║        Built for BCA Students | by Your Name         ║
╚══════════════════════════════════════════════════════╝

Features:
  - Multiple categories (Python, General Knowledge, Math)
  - 4 difficulty levels (Easy, Medium, Hard, Mixed)
  - Timer per question
  - Score tracking with grade
  - Highscore saved to file
  - Colourful terminal output
"""

import random
import time
import os
import json
from datetime import datetime

# ─────────────────────────────────────────────
#  COLOURS (works on Windows + Linux/Mac)
# ─────────────────────────────────────────────
class C:
    RESET  = "\033[0m"
    BOLD   = "\033[1m"
    CYAN   = "\033[96m"
    GREEN  = "\033[92m"
    RED    = "\033[91m"
    YELLOW = "\033[93m"
    PURPLE = "\033[95m"
    BLUE   = "\033[94m"
    WHITE  = "\033[97m"
    GREY   = "\033[90m"

def clr(text, colour):
    return f"{colour}{text}{C.RESET}"

# ─────────────────────────────────────────────
#  QUESTION BANK
# ─────────────────────────────────────────────
QUESTIONS = {
    "Python": {
        "easy": [
            {
                "q": "Which keyword is used to define a function in Python?",
                "options": ["A) func", "B) def", "C) define", "D) function"],
                "answer": "B",
                "explanation": "'def' is the keyword used to define a function in Python."
            },
            {
                "q": "What data type does input() always return?",
                "options": ["A) int", "B) float", "C) str", "D) list"],
                "answer": "C",
                "explanation": "input() always returns a string (str). Use int() or float() to convert."
            },
            {
                "q": "What is the output of: print(2 ** 3)?",
                "options": ["A) 6", "B) 8", "C) 9", "D) 5"],
                "answer": "B",
                "explanation": "** is the exponentiation operator. 2**3 = 2×2×2 = 8."
            },
            {
                "q": "Which of these is a valid Python comment?",
                "options": ["A) // comment", "B) /* comment */", "C) # comment", "D) <!-- comment -->"],
                "answer": "C",
                "explanation": "Python uses # for single-line comments."
            },
            {
                "q": "How do you create an empty list in Python?",
                "options": ["A) list = {}", "B) list = []", "C) list = ()", "D) list = <>"],
                "answer": "B",
                "explanation": "Square brackets [] create an empty list. {} is a dict, () is a tuple."
            },
        ],
        "medium": [
            {
                "q": "What does the 'len()' function return for len([1, 2, 3])?",
                "options": ["A) 2", "B) 3", "C) 4", "D) Error"],
                "answer": "B",
                "explanation": "len() returns the number of items in the list. [1,2,3] has 3 items."
            },
            {
                "q": "What is the output of: print(type(3.14))?",
                "options": ["A) <class 'int'>", "B) <class 'str'>", "C) <class 'float'>", "D) <class 'double'>"],
                "answer": "C",
                "explanation": "3.14 is a floating point number, so its type is float."
            },
            {
                "q": "Which method adds an item to the END of a list?",
                "options": ["A) list.add()", "B) list.insert()", "C) list.append()", "D) list.push()"],
                "answer": "C",
                "explanation": "append() adds an element to the end of a list."
            },
            {
                "q": "What does 10 % 3 evaluate to?",
                "options": ["A) 3", "B) 1", "C) 0", "D) 3.33"],
                "answer": "B",
                "explanation": "% is the modulo (remainder) operator. 10 ÷ 3 = 3 remainder 1."
            },
            {
                "q": "How do you open a file named 'data.txt' for reading in Python?",
                "options": [
                    "A) open('data.txt', 'w')",
                    "B) open('data.txt', 'r')",
                    "C) open('data.txt', 'a')",
                    "D) file('data.txt')"
                ],
                "answer": "B",
                "explanation": "'r' mode opens a file for reading. 'w' writes, 'a' appends."
            },
        ],
        "hard": [
            {
                "q": "What is the output of: [x**2 for x in range(4)]?",
                "options": ["A) [1, 4, 9, 16]", "B) [0, 1, 4, 9]", "C) [0, 2, 4, 6]", "D) [1, 2, 3, 4]"],
                "answer": "B",
                "explanation": "range(4) = 0,1,2,3. Squaring gives 0,1,4,9."
            },
            {
                "q": "Which of these creates a TUPLE?",
                "options": ["A) t = [1, 2, 3]", "B) t = {1, 2, 3}", "C) t = (1, 2, 3)", "D) t = <1, 2, 3>"],
                "answer": "C",
                "explanation": "Tuples use parentheses (). They are immutable unlike lists."
            },
            {
                "q": "What will dict.get('key', 'default') return if 'key' does NOT exist?",
                "options": ["A) None", "B) Error", "C) 'default'", "D) 0"],
                "answer": "C",
                "explanation": "dict.get(key, default) returns the default value if the key is missing."
            },
            {
                "q": "What does *args allow in a function definition?",
                "options": [
                    "A) Only keyword arguments",
                    "B) Any number of positional arguments",
                    "C) Exactly 2 arguments",
                    "D) No arguments"
                ],
                "answer": "B",
                "explanation": "*args collects any number of positional arguments into a tuple."
            },
            {
                "q": "Which Python data structure uses key-value pairs?",
                "options": ["A) List", "B) Tuple", "C) Set", "D) Dictionary"],
                "answer": "D",
                "explanation": "Dictionaries store data as key:value pairs. e.g. {'name': 'Alice'}"
            },
        ],
    },

    "General Knowledge": {
        "easy": [
            {
                "q": "What does CPU stand for?",
                "options": ["A) Central Processing Unit", "B) Computer Personal Unit", "C) Core Power Unit", "D) Central Power Utility"],
                "answer": "A",
                "explanation": "CPU = Central Processing Unit — the brain of the computer."
            },
            {
                "q": "What does 'www' stand for?",
                "options": ["A) World Wide Web", "B) Wide World Website", "C) Web World Wide", "D) World Web Works"],
                "answer": "A",
                "explanation": "WWW = World Wide Web, invented by Tim Berners-Lee in 1989."
            },
            {
                "q": "Which company created Python?",
                "options": ["A) Google", "B) Microsoft", "C) Guido van Rossum / CWI", "D) Apple"],
                "answer": "C",
                "explanation": "Python was created by Guido van Rossum and first released in 1991."
            },
        ],
        "medium": [
            {
                "q": "What does RAM stand for?",
                "options": ["A) Read Access Memory", "B) Random Access Memory", "C) Rapid Array Memory", "D) Real Active Module"],
                "answer": "B",
                "explanation": "RAM = Random Access Memory. It's temporary, fast storage for running programs."
            },
            {
                "q": "Which language is primarily used for styling web pages?",
                "options": ["A) HTML", "B) JavaScript", "C) CSS", "D) Python"],
                "answer": "C",
                "explanation": "CSS (Cascading Style Sheets) controls the visual appearance of web pages."
            },
            {
                "q": "What does 'SQL' stand for?",
                "options": [
                    "A) Structured Query Language",
                    "B) Simple Query Language",
                    "C) System Query Logic",
                    "D) Sequential Query List"
                ],
                "answer": "A",
                "explanation": "SQL = Structured Query Language — used to manage relational databases."
            },
        ],
        "hard": [
            {
                "q": "In binary, what is the decimal value of 1010?",
                "options": ["A) 8", "B) 10", "C) 12", "D) 6"],
                "answer": "B",
                "explanation": "1010 in binary = 1×8 + 0×4 + 1×2 + 0×1 = 10 in decimal."
            },
            {
                "q": "Which sorting algorithm has an average time complexity of O(n log n)?",
                "options": ["A) Bubble Sort", "B) Selection Sort", "C) Merge Sort", "D) Linear Search"],
                "answer": "C",
                "explanation": "Merge Sort has O(n log n) average complexity — much better than O(n²) sorts."
            },
        ],
    },

    "Math": {
        "easy": [
            {
                "q": "What is 15% of 200?",
                "options": ["A) 20", "B) 25", "C) 30", "D) 35"],
                "answer": "C",
                "explanation": "15% × 200 = 0.15 × 200 = 30."
            },
            {
                "q": "What is the square root of 144?",
                "options": ["A) 11", "B) 12", "C) 13", "D) 14"],
                "answer": "B",
                "explanation": "√144 = 12, because 12 × 12 = 144."
            },
        ],
        "medium": [
            {
                "q": "If a = 5 and b = 3, what is a² + b²?",
                "options": ["A) 34", "B) 64", "C) 30", "D) 28"],
                "answer": "A",
                "explanation": "5² + 3² = 25 + 9 = 34."
            },
            {
                "q": "What is the value of π (pi) to 2 decimal places?",
                "options": ["A) 3.12", "B) 3.14", "C) 3.16", "D) 3.41"],
                "answer": "B",
                "explanation": "π ≈ 3.14159... Rounded to 2 decimals = 3.14."
            },
        ],
        "hard": [
            {
                "q": "What is the result of: 2³ × 3² ÷ 6?",
                "options": ["A) 10", "B) 12", "C) 14", "D) 16"],
                "answer": "B",
                "explanation": "2³=8, 3²=9, 8×9=72, 72÷6=12."
            },
        ],
    },
}

HIGHSCORE_FILE = "highscores.json"
TIME_LIMIT = 20  # seconds per question


# ─────────────────────────────────────────────
#  UTILITY FUNCTIONS
# ─────────────────────────────────────────────
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def print_banner():
    clear_screen()
    banner = f"""
{C.CYAN}{C.BOLD}
  ██████  ██    ██ ██ ███████     ███████ ███████
 ██    ██ ██    ██ ██    ███      ██   ██ ██
 ██    ██ ██    ██ ██   ███       ███████ ███████
 ██ ▄▄ ██ ██    ██ ██  ███        ██        ██
  ██████   ██████  ██ ███████     ██     ███████
{C.RESET}
{C.PURPLE}            🐍  PYTHON QUIZ APP  🐍{C.RESET}
{C.GREY}         ─────────────────────────────────{C.RESET}
    """
    print(banner)

def print_separator(char="─", length=52, colour=C.GREY):
    print(clr(char * length, colour))

def get_highscores():
    if os.path.exists(HIGHSCORE_FILE):
        with open(HIGHSCORE_FILE, "r") as f:
            return json.load(f)
    return []

def save_highscore(name, score, total, category, difficulty, duration):
    scores = get_highscores()
    scores.append({
        "name": name,
        "score": score,
        "total": total,
        "pct": round((score/total)*100, 1),
        "category": category,
        "difficulty": difficulty,
        "duration": round(duration, 1),
        "date": datetime.now().strftime("%d %b %Y %H:%M")
    })
    scores.sort(key=lambda x: x["pct"], reverse=True)
    scores = scores[:10]  # keep top 10
    with open(HIGHSCORE_FILE, "w") as f:
        json.dump(scores, f, indent=2)

def show_highscores():
    scores = get_highscores()
    print_banner()
    print(clr("  🏆  TOP 10 HIGHSCORES", C.YELLOW + C.BOLD))
    print_separator()
    if not scores:
        print(clr("  No scores yet! Play a game first.", C.GREY))
    else:
        print(f"  {'#':<3} {'Name':<14} {'Score':<8} {'%':<7} {'Category':<18} {'Date'}")
        print_separator(char="·")
        for i, s in enumerate(scores, 1):
            medal = ["🥇","🥈","🥉"][i-1] if i <= 3 else f" {i}."
            pct_colour = C.GREEN if s['pct'] >= 70 else C.YELLOW if s['pct'] >= 50 else C.RED
            print(f"  {medal:<4} {s['name']:<14} {s['score']}/{s['total']:<6} "
                  f"{clr(str(s['pct'])+'%', pct_colour):<18} {s['category']:<18} {s['date']}")
    print_separator()
    input(clr("\n  Press Enter to go back...", C.GREY))

def get_grade(pct):
    if pct >= 90: return "A+", "Outstanding! 🌟"
    if pct >= 75: return "A",  "Excellent! 🎉"
    if pct >= 60: return "B",  "Good job! 👍"
    if pct >= 45: return "C",  "Not bad! Keep practising. 📚"
    if pct >= 30: return "D",  "Needs improvement. 💪"
    return "F", "Keep studying, you'll get there! 🔄"

def timed_input(prompt, timeout=TIME_LIMIT):
    """Input with a countdown timer (best-effort — works on Unix fully, Windows partially)."""
    import threading
    result = [None]
    answered = [False]

    def get_input():
        try:
            result[0] = input(prompt)
        except:
            result[0] = ""
        answered[0] = True

    t = threading.Thread(target=get_input, daemon=True)
    t.start()

    start = time.time()
    while not answered[0]:
        elapsed = time.time() - start
        remaining = timeout - elapsed
        if remaining <= 0:
            print(clr(f"\n  ⏰  Time's up!", C.RED))
            return None, timeout
        time.sleep(0.1)

    return result[0], time.time() - start


# ─────────────────────────────────────────────
#  QUIZ ENGINE
# ─────────────────────────────────────────────
def build_question_set(category, difficulty, num_questions):
    """Collect questions based on settings."""
    bank = []

    cats = list(QUESTIONS.keys()) if category == "All" else [category]
    diffs = ["easy", "medium", "hard"] if difficulty == "mixed" else [difficulty]

    for cat in cats:
        for diff in diffs:
            if cat in QUESTIONS and diff in QUESTIONS[cat]:
                for q in QUESTIONS[cat][diff]:
                    bank.append({**q, "category": cat, "difficulty": diff})

    random.shuffle(bank)
    return bank[:num_questions]


def run_quiz(player_name, category, difficulty, num_questions):
    questions = build_question_set(category, difficulty, num_questions)

    if not questions:
        print(clr("\n  ⚠  Not enough questions for that combination. Try 'All' categories.", C.YELLOW))
        time.sleep(2)
        return

    score = 0
    total = len(questions)
    wrong_answers = []
    total_time = 0

    for i, q in enumerate(questions, 1):
        clear_screen()

        # ── Header ──
        progress = "█" * i + "░" * (total - i)
        print(clr(f"\n  [{progress}]  Q{i}/{total}  |  {q['category']}  |  {q['difficulty'].upper()}  |  ⏱ {TIME_LIMIT}s", C.GREY))
        print_separator(colour=C.BLUE)

        # ── Question ──
        print(f"\n  {clr(f'Q{i}.', C.CYAN + C.BOLD)}  {clr(q['q'], C.WHITE + C.BOLD)}\n")
        for opt in q["options"]:
            print(f"      {clr(opt, C.TEXT if hasattr(C,'TEXT') else C.RESET)}")

        print()
        print_separator(char="·", colour=C.GREY)

        # ── Get Answer ──
        start = time.time()
        raw = input(clr(f"  Your answer (A/B/C/D) ⏱ [{TIME_LIMIT}s]: ", C.YELLOW)).strip().upper()
        elapsed = time.time() - start

        total_time += elapsed

        # ── Time check ──
        if elapsed > TIME_LIMIT:
            print(clr("\n  ⏰  Too slow! Moving on.", C.RED))
            wrong_answers.append({**q, "your_answer": "⏰ Timeout"})
            time.sleep(1.5)
            continue

        if raw not in ["A", "B", "C", "D"]:
            print(clr("  ⚠  Invalid input — skipping.", C.YELLOW))
            wrong_answers.append({**q, "your_answer": raw or "?"})
            time.sleep(1.2)
            continue

        # ── Evaluate ──
        correct = q["answer"]
        if raw == correct:
            score += 1
            print(clr(f"\n  ✅  CORRECT!  +1 point  ({elapsed:.1f}s)", C.GREEN + C.BOLD))
        else:
            print(clr(f"\n  ❌  WRONG!  Correct answer: {correct}", C.RED + C.BOLD))
            wrong_answers.append({**q, "your_answer": raw})

        print(clr(f"  💡  {q['explanation']}", C.GREY))
        time.sleep(2.2)

    # ── Results Screen ──
    clear_screen()
    pct = round((score / total) * 100, 1)
    grade, message = get_grade(pct)

    print(f"""
{C.CYAN}{C.BOLD}  ╔══════════════════════════════════════╗
  ║           QUIZ COMPLETE! 🎉           ║
  ╚══════════════════════════════════════╝{C.RESET}

  {clr('Player:', C.GREY)}   {clr(player_name, C.WHITE + C.BOLD)}
  {clr('Category:', C.GREY)} {category}  |  {clr('Difficulty:', C.GREY)} {difficulty.title()}
  {clr('Score:', C.GREY)}    {clr(f'{score} / {total}', C.CYAN + C.BOLD)}
  {clr('Accuracy:', C.GREY)} {clr(f'{pct}%', C.GREEN if pct >= 60 else C.RED)}
  {clr('Grade:', C.GREY)}    {clr(grade, C.YELLOW + C.BOLD)}
  {clr('Time:', C.GREY)}     {clr(f'{total_time:.1f}s total  ({(total_time/total):.1f}s avg/question)', C.GREY)}

  {clr(message, C.PURPLE + C.BOLD)}
    """)

    # Save score
    save_highscore(player_name, score, total, category, difficulty, total_time)

    # Show wrong answers
    if wrong_answers:
        print_separator()
        print(clr(f"\n  📝  Review — {len(wrong_answers)} wrong answer(s):\n", C.YELLOW))
        for j, w in enumerate(wrong_answers, 1):
            print(f"  {clr(str(j)+'.', C.GREY)} {w['q']}")
            print(f"     {clr('You answered:', C.RED)}  {w['your_answer']}   {clr('Correct:', C.GREEN)}  {w['answer']}")
            print(f"     {clr(w['explanation'], C.GREY)}\n")

    print_separator()
    input(clr("  Press Enter to return to menu...", C.GREY))


# ─────────────────────────────────────────────
#  MENU SYSTEM
# ─────────────────────────────────────────────
def menu_choose(prompt, options):
    """Display a numbered menu and return chosen value."""
    print(f"\n  {clr(prompt, C.CYAN + C.BOLD)}\n")
    for i, (label, _) in enumerate(options, 1):
        print(f"    {clr(str(i)+'.', C.YELLOW)}  {label}")
    print()
    while True:
        choice = input(clr("  Enter number: ", C.WHITE)).strip()
        if choice.isdigit() and 1 <= int(choice) <= len(options):
            return options[int(choice)-1][1]
        print(clr("  ⚠  Invalid choice, try again.", C.RED))


def main():
    # Get player name once
    print_banner()
    print(clr("  Welcome! Let's set you up.\n", C.PURPLE))
    player_name = input(clr("  Enter your name: ", C.CYAN)).strip() or "Player"

    while True:
        print_banner()
        print(clr(f"  Hello, {player_name}! 👋\n", C.GREEN))
        print_separator()

        print(f"""
  {clr('1.', C.YELLOW)}  🎮  Start Quiz
  {clr('2.', C.YELLOW)}  🏆  View Highscores
  {clr('3.', C.YELLOW)}  👤  Change Name
  {clr('4.', C.YELLOW)}  ❌  Exit
        """)
        print_separator()

        choice = input(clr("  Choose an option (1-4): ", C.WHITE)).strip()

        if choice == "1":
            print_banner()

            # Category
            category = menu_choose("Choose a Category:", [
                ("Python",           "Python"),
                ("General Knowledge","General Knowledge"),
                ("Math",             "Math"),
                ("All Categories",   "All"),
            ])

            # Difficulty
            difficulty = menu_choose("Choose Difficulty:", [
                ("🟢  Easy",   "easy"),
                ("🟡  Medium", "medium"),
                ("🔴  Hard",   "hard"),
                ("🌀  Mixed",  "mixed"),
            ])

            # Number of questions
            num = menu_choose("How many questions?", [
                ("5  questions  (Quick)",  5),
                ("10 questions  (Normal)", 10),
                ("15 questions  (Full)",   15),
            ])

            # Countdown
            clear_screen()
            print(clr("\n\n  Get ready...\n", C.PURPLE + C.BOLD))
            for i in range(3, 0, -1):
                print(clr(f"         {i}...", C.CYAN + C.BOLD))
                time.sleep(0.9)
            print(clr("      🚀  GO!\n", C.GREEN + C.BOLD))
            time.sleep(0.5)

            run_quiz(player_name, category, difficulty, num)

        elif choice == "2":
            show_highscores()

        elif choice == "3":
            print_banner()
            player_name = input(clr("  Enter new name: ", C.CYAN)).strip() or player_name
            print(clr(f"\n  ✅  Name updated to: {player_name}", C.GREEN))
            time.sleep(1.2)

        elif choice == "4":
            print_banner()
            print(clr("  Thanks for playing! Keep learning! 🐍\n", C.CYAN + C.BOLD))
            break

        else:
            print(clr("  ⚠  Invalid choice!", C.RED))
            time.sleep(0.8)


# ─────────────────────────────────────────────
#  ENTRY POINT
# ─────────────────────────────────────────────
if __name__ == "__main__":
    try:
        # Enable ANSI colours on Windows
        os.system("")
        main()
    except KeyboardInterrupt:
        print(clr("\n\n  Goodbye! 👋\n", C.CYAN))